DROP TABLE IF EXISTS UserAccount CASCADE;
DROP TABLE IF EXISTS OrderStatus CASCADE;
DROP TABLE IF EXISTS UserOrder CASCADE;
DROP TABLE IF EXISTS TransactionType CASCADE;
DROP TABLE IF EXISTS Transaction CASCADE;
DROP TABLE IF EXISTS Queue CASCADE;
